package com.hnqj.model;

import java.util.Date;

public class Collectiongraph {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collectiongraph.uid
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collectiongraph.graphid
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    private String graphid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collectiongraph.collectionuserid
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    private String collectionuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collectiongraph.addtime
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    private Date addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collectiongraph.flag
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    private Short flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collectiongraph.backup1
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    private String backup1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collectiongraph.backup2
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    private String backup2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collectiongraph.backup3
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    private String backup3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collectiongraph.uid
     *
     * @return the value of tb_collectiongraph.uid
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collectiongraph.uid
     *
     * @param uid the value for tb_collectiongraph.uid
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collectiongraph.graphid
     *
     * @return the value of tb_collectiongraph.graphid
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    public String getGraphid() {
        return graphid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collectiongraph.graphid
     *
     * @param graphid the value for tb_collectiongraph.graphid
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    public void setGraphid(String graphid) {
        this.graphid = graphid == null ? null : graphid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collectiongraph.collectionuserid
     *
     * @return the value of tb_collectiongraph.collectionuserid
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    public String getCollectionuserid() {
        return collectionuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collectiongraph.collectionuserid
     *
     * @param collectionuserid the value for tb_collectiongraph.collectionuserid
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    public void setCollectionuserid(String collectionuserid) {
        this.collectionuserid = collectionuserid == null ? null : collectionuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collectiongraph.addtime
     *
     * @return the value of tb_collectiongraph.addtime
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collectiongraph.addtime
     *
     * @param addtime the value for tb_collectiongraph.addtime
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collectiongraph.flag
     *
     * @return the value of tb_collectiongraph.flag
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    public Short getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collectiongraph.flag
     *
     * @param flag the value for tb_collectiongraph.flag
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    public void setFlag(Short flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collectiongraph.backup1
     *
     * @return the value of tb_collectiongraph.backup1
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    public String getBackup1() {
        return backup1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collectiongraph.backup1
     *
     * @param backup1 the value for tb_collectiongraph.backup1
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    public void setBackup1(String backup1) {
        this.backup1 = backup1 == null ? null : backup1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collectiongraph.backup2
     *
     * @return the value of tb_collectiongraph.backup2
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    public String getBackup2() {
        return backup2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collectiongraph.backup2
     *
     * @param backup2 the value for tb_collectiongraph.backup2
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    public void setBackup2(String backup2) {
        this.backup2 = backup2 == null ? null : backup2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collectiongraph.backup3
     *
     * @return the value of tb_collectiongraph.backup3
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    public String getBackup3() {
        return backup3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collectiongraph.backup3
     *
     * @param backup3 the value for tb_collectiongraph.backup3
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    public void setBackup3(String backup3) {
        this.backup3 = backup3 == null ? null : backup3.trim();
    }
}