package com.hnqj.model;

import java.util.Date;

public class Collectionsubmission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collectionsubmission.uid
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collectionsubmission.submissionid
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    private String submissionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collectionsubmission.collectionuserid
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    private String collectionuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collectionsubmission.addtime
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    private Date addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collectionsubmission.flag
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    private Short flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collectionsubmission.backup1
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    private String backup1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collectionsubmission.backup2
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    private String backup2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collectionsubmission.backup3
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    private String backup3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collectionsubmission.uid
     *
     * @return the value of tb_collectionsubmission.uid
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collectionsubmission.uid
     *
     * @param uid the value for tb_collectionsubmission.uid
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collectionsubmission.submissionid
     *
     * @return the value of tb_collectionsubmission.submissionid
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    public String getSubmissionid() {
        return submissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collectionsubmission.submissionid
     *
     * @param submissionid the value for tb_collectionsubmission.submissionid
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    public void setSubmissionid(String submissionid) {
        this.submissionid = submissionid == null ? null : submissionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collectionsubmission.collectionuserid
     *
     * @return the value of tb_collectionsubmission.collectionuserid
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    public String getCollectionuserid() {
        return collectionuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collectionsubmission.collectionuserid
     *
     * @param collectionuserid the value for tb_collectionsubmission.collectionuserid
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    public void setCollectionuserid(String collectionuserid) {
        this.collectionuserid = collectionuserid == null ? null : collectionuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collectionsubmission.addtime
     *
     * @return the value of tb_collectionsubmission.addtime
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collectionsubmission.addtime
     *
     * @param addtime the value for tb_collectionsubmission.addtime
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collectionsubmission.flag
     *
     * @return the value of tb_collectionsubmission.flag
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    public Short getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collectionsubmission.flag
     *
     * @param flag the value for tb_collectionsubmission.flag
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    public void setFlag(Short flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collectionsubmission.backup1
     *
     * @return the value of tb_collectionsubmission.backup1
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    public String getBackup1() {
        return backup1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collectionsubmission.backup1
     *
     * @param backup1 the value for tb_collectionsubmission.backup1
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    public void setBackup1(String backup1) {
        this.backup1 = backup1 == null ? null : backup1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collectionsubmission.backup2
     *
     * @return the value of tb_collectionsubmission.backup2
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    public String getBackup2() {
        return backup2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collectionsubmission.backup2
     *
     * @param backup2 the value for tb_collectionsubmission.backup2
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    public void setBackup2(String backup2) {
        this.backup2 = backup2 == null ? null : backup2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collectionsubmission.backup3
     *
     * @return the value of tb_collectionsubmission.backup3
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    public String getBackup3() {
        return backup3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collectionsubmission.backup3
     *
     * @param backup3 the value for tb_collectionsubmission.backup3
     *
     * @mbg.generated Sat Mar 03 18:53:32 CST 2018
     */
    public void setBackup3(String backup3) {
        this.backup3 = backup3 == null ? null : backup3.trim();
    }
}