package com.hnqj.model;

import java.math.BigDecimal;
import java.util.Date;

public class Dealuidchild {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dealuidchild.dealuid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String dealuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dealuidchild.worksid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String worksid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dealuidchild.worksprice
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private BigDecimal worksprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dealuidchild.worksname
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String worksname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dealuidchild.merchid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String merchid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dealuidchild.merchname
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String merchname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dealuidchild.addtime
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private Date addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dealuidchild.payuserid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String payuserid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dealuidchild.dealuid
     *
     * @return the value of tb_dealuidchild.dealuid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getDealuid() {
        return dealuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dealuidchild.dealuid
     *
     * @param dealuid the value for tb_dealuidchild.dealuid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setDealuid(String dealuid) {
        this.dealuid = dealuid == null ? null : dealuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dealuidchild.worksid
     *
     * @return the value of tb_dealuidchild.worksid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getWorksid() {
        return worksid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dealuidchild.worksid
     *
     * @param worksid the value for tb_dealuidchild.worksid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setWorksid(String worksid) {
        this.worksid = worksid == null ? null : worksid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dealuidchild.worksprice
     *
     * @return the value of tb_dealuidchild.worksprice
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public BigDecimal getWorksprice() {
        return worksprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dealuidchild.worksprice
     *
     * @param worksprice the value for tb_dealuidchild.worksprice
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setWorksprice(BigDecimal worksprice) {
        this.worksprice = worksprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dealuidchild.worksname
     *
     * @return the value of tb_dealuidchild.worksname
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getWorksname() {
        return worksname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dealuidchild.worksname
     *
     * @param worksname the value for tb_dealuidchild.worksname
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setWorksname(String worksname) {
        this.worksname = worksname == null ? null : worksname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dealuidchild.merchid
     *
     * @return the value of tb_dealuidchild.merchid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getMerchid() {
        return merchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dealuidchild.merchid
     *
     * @param merchid the value for tb_dealuidchild.merchid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setMerchid(String merchid) {
        this.merchid = merchid == null ? null : merchid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dealuidchild.merchname
     *
     * @return the value of tb_dealuidchild.merchname
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getMerchname() {
        return merchname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dealuidchild.merchname
     *
     * @param merchname the value for tb_dealuidchild.merchname
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setMerchname(String merchname) {
        this.merchname = merchname == null ? null : merchname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dealuidchild.addtime
     *
     * @return the value of tb_dealuidchild.addtime
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dealuidchild.addtime
     *
     * @param addtime the value for tb_dealuidchild.addtime
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dealuidchild.payuserid
     *
     * @return the value of tb_dealuidchild.payuserid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getPayuserid() {
        return payuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dealuidchild.payuserid
     *
     * @param payuserid the value for tb_dealuidchild.payuserid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setPayuserid(String payuserid) {
        this.payuserid = payuserid == null ? null : payuserid.trim();
    }
}