package com.hnqj.model;

import java.util.Date;

public class Download {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_download.uid
     *
     * @mbg.generated Wed Jan 31 07:49:30 CST 2018
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_download.payuserid
     *
     * @mbg.generated Wed Jan 31 07:49:30 CST 2018
     */
    private String payuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_download.workid
     *
     * @mbg.generated Wed Jan 31 07:49:30 CST 2018
     */
    private String workid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_download.price
     *
     * @mbg.generated Wed Jan 31 07:49:30 CST 2018
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_download.workname
     *
     * @mbg.generated Wed Jan 31 07:49:30 CST 2018
     */
    private String workname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_download.paydate
     *
     * @mbg.generated Wed Jan 31 07:49:30 CST 2018
     */
    private Date paydate;

    private String merchid;

    private String merchname;

    private String smallurl;



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_download.uid
     *
     * @return the value of pt_download.uid
     *
     * @mbg.generated Wed Jan 31 07:49:30 CST 2018
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_download.uid
     *
     * @param uid the value for pt_download.uid
     *
     * @mbg.generated Wed Jan 31 07:49:30 CST 2018
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_download.payuserid
     *
     * @return the value of pt_download.payuserid
     *
     * @mbg.generated Wed Jan 31 07:49:30 CST 2018
     */
    public String getPayuserid() {
        return payuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_download.payuserid
     *
     * @param payuserid the value for pt_download.payuserid
     *
     * @mbg.generated Wed Jan 31 07:49:30 CST 2018
     */
    public void setPayuserid(String payuserid) {
        this.payuserid = payuserid == null ? null : payuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_download.workid
     *
     * @return the value of pt_download.workid
     *
     * @mbg.generated Wed Jan 31 07:49:30 CST 2018
     */
    public String getWorkid() {
        return workid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_download.workid
     *
     * @param workid the value for pt_download.workid
     *
     * @mbg.generated Wed Jan 31 07:49:30 CST 2018
     */
    public void setWorkid(String workid) {
        this.workid = workid == null ? null : workid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_download.price
     *
     * @return the value of pt_download.price
     *
     * @mbg.generated Wed Jan 31 07:49:30 CST 2018
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_download.price
     *
     * @param price the value for pt_download.price
     *
     * @mbg.generated Wed Jan 31 07:49:30 CST 2018
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_download.workname
     *
     * @return the value of pt_download.workname
     *
     * @mbg.generated Wed Jan 31 07:49:30 CST 2018
     */
    public String getWorkname() {
        return workname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_download.workname
     *
     * @param workname the value for pt_download.workname
     *
     * @mbg.generated Wed Jan 31 07:49:30 CST 2018
     */
    public void setWorkname(String workname) {
        this.workname = workname == null ? null : workname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_download.paydate
     *
     * @return the value of pt_download.paydate
     *
     * @mbg.generated Wed Jan 31 07:49:30 CST 2018
     */
    public Date getPaydate() {
        return paydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_download.paydate
     *
     * @param paydate the value for pt_download.paydate
     *
     * @mbg.generated Wed Jan 31 07:49:30 CST 2018
     */
    public void setPaydate(Date paydate) {
        this.paydate = paydate;
    }

    public String getMerchid() {
        return merchid;
    }

    public void setMerchid(String merchid) {
        this.merchid = merchid;
    }

    public String getMerchname() {
        return merchname;
    }

    public void setMerchname(String merchname) {
        this.merchname = merchname;
    }

    public String getSmallurl() {
        return smallurl;
    }

    public void setSmallurl(String smallurl) {
        this.smallurl = smallurl;
    }
}