package com.hnqj.model;

import java.util.Date;

public class FocusOther {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_focus_other.user_id
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_focus_other.focus_userid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String focusUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_focus_other.focus_merchid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String focusMerchid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_focus_other.add_date
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private Date addDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_focus_other.user_id
     *
     * @return the value of tb_focus_other.user_id
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_focus_other.user_id
     *
     * @param userId the value for tb_focus_other.user_id
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_focus_other.focus_userid
     *
     * @return the value of tb_focus_other.focus_userid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getFocusUserid() {
        return focusUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_focus_other.focus_userid
     *
     * @param focusUserid the value for tb_focus_other.focus_userid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setFocusUserid(String focusUserid) {
        this.focusUserid = focusUserid == null ? null : focusUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_focus_other.focus_merchid
     *
     * @return the value of tb_focus_other.focus_merchid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getFocusMerchid() {
        return focusMerchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_focus_other.focus_merchid
     *
     * @param focusMerchid the value for tb_focus_other.focus_merchid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setFocusMerchid(String focusMerchid) {
        this.focusMerchid = focusMerchid == null ? null : focusMerchid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_focus_other.add_date
     *
     * @return the value of tb_focus_other.add_date
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public Date getAddDate() {
        return addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_focus_other.add_date
     *
     * @param addDate the value for tb_focus_other.add_date
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }
}