package com.hnqj.model;

import java.util.Date;

public class Graphleavingmsg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_graphleavingmsg.uid
     *
     * @mbg.generated Sat Mar 03 17:03:20 CST 2018
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_graphleavingmsg.graphid
     *
     * @mbg.generated Sat Mar 03 17:03:20 CST 2018
     */
    private String graphid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_graphleavingmsg.leavinguserid
     *
     * @mbg.generated Sat Mar 03 17:03:20 CST 2018
     */
    private String leavinguserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_graphleavingmsg.content
     *
     * @mbg.generated Sat Mar 03 17:03:20 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_graphleavingmsg.addtime
     *
     * @mbg.generated Sat Mar 03 17:03:20 CST 2018
     */
    private Date addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_graphleavingmsg.backup1
     *
     * @mbg.generated Sat Mar 03 17:03:20 CST 2018
     */
    private String backup1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_graphleavingmsg.backup2
     *
     * @mbg.generated Sat Mar 03 17:03:20 CST 2018
     */
    private String backup2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_graphleavingmsg.backup3
     *
     * @mbg.generated Sat Mar 03 17:03:20 CST 2018
     */
    private String backup3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_graphleavingmsg.uid
     *
     * @return the value of tb_graphleavingmsg.uid
     *
     * @mbg.generated Sat Mar 03 17:03:20 CST 2018
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_graphleavingmsg.uid
     *
     * @param uid the value for tb_graphleavingmsg.uid
     *
     * @mbg.generated Sat Mar 03 17:03:20 CST 2018
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_graphleavingmsg.graphid
     *
     * @return the value of tb_graphleavingmsg.graphid
     *
     * @mbg.generated Sat Mar 03 17:03:20 CST 2018
     */
    public String getGraphid() {
        return graphid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_graphleavingmsg.graphid
     *
     * @param graphid the value for tb_graphleavingmsg.graphid
     *
     * @mbg.generated Sat Mar 03 17:03:20 CST 2018
     */
    public void setGraphid(String graphid) {
        this.graphid = graphid == null ? null : graphid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_graphleavingmsg.leavinguserid
     *
     * @return the value of tb_graphleavingmsg.leavinguserid
     *
     * @mbg.generated Sat Mar 03 17:03:20 CST 2018
     */
    public String getLeavinguserid() {
        return leavinguserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_graphleavingmsg.leavinguserid
     *
     * @param leavinguserid the value for tb_graphleavingmsg.leavinguserid
     *
     * @mbg.generated Sat Mar 03 17:03:20 CST 2018
     */
    public void setLeavinguserid(String leavinguserid) {
        this.leavinguserid = leavinguserid == null ? null : leavinguserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_graphleavingmsg.content
     *
     * @return the value of tb_graphleavingmsg.content
     *
     * @mbg.generated Sat Mar 03 17:03:20 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_graphleavingmsg.content
     *
     * @param content the value for tb_graphleavingmsg.content
     *
     * @mbg.generated Sat Mar 03 17:03:20 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_graphleavingmsg.addtime
     *
     * @return the value of tb_graphleavingmsg.addtime
     *
     * @mbg.generated Sat Mar 03 17:03:20 CST 2018
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_graphleavingmsg.addtime
     *
     * @param addtime the value for tb_graphleavingmsg.addtime
     *
     * @mbg.generated Sat Mar 03 17:03:20 CST 2018
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_graphleavingmsg.backup1
     *
     * @return the value of tb_graphleavingmsg.backup1
     *
     * @mbg.generated Sat Mar 03 17:03:20 CST 2018
     */
    public String getBackup1() {
        return backup1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_graphleavingmsg.backup1
     *
     * @param backup1 the value for tb_graphleavingmsg.backup1
     *
     * @mbg.generated Sat Mar 03 17:03:20 CST 2018
     */
    public void setBackup1(String backup1) {
        this.backup1 = backup1 == null ? null : backup1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_graphleavingmsg.backup2
     *
     * @return the value of tb_graphleavingmsg.backup2
     *
     * @mbg.generated Sat Mar 03 17:03:20 CST 2018
     */
    public String getBackup2() {
        return backup2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_graphleavingmsg.backup2
     *
     * @param backup2 the value for tb_graphleavingmsg.backup2
     *
     * @mbg.generated Sat Mar 03 17:03:20 CST 2018
     */
    public void setBackup2(String backup2) {
        this.backup2 = backup2 == null ? null : backup2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_graphleavingmsg.backup3
     *
     * @return the value of tb_graphleavingmsg.backup3
     *
     * @mbg.generated Sat Mar 03 17:03:20 CST 2018
     */
    public String getBackup3() {
        return backup3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_graphleavingmsg.backup3
     *
     * @param backup3 the value for tb_graphleavingmsg.backup3
     *
     * @mbg.generated Sat Mar 03 17:03:20 CST 2018
     */
    public void setBackup3(String backup3) {
        this.backup3 = backup3 == null ? null : backup3.trim();
    }
}