package com.hnqj.model;

import java.util.Date;

public class Leavemsg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_leavemsg.uid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_leavemsg.userid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_leavemsg.msgContent
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String msgcontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_leavemsg.msgtime
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private Date msgtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_leavemsg.replyuserid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String replyuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_leavemsg.replycontent
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String replycontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_leavemsg.replytime
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private Date replytime;

    private String workid;

    private String merchid;



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_leavemsg.uid
     *
     * @return the value of tb_leavemsg.uid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_leavemsg.uid
     *
     * @param uid the value for tb_leavemsg.uid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_leavemsg.userid
     *
     * @return the value of tb_leavemsg.userid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_leavemsg.userid
     *
     * @param userid the value for tb_leavemsg.userid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_leavemsg.msgContent
     *
     * @return the value of tb_leavemsg.msgContent
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getMsgcontent() {
        return msgcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_leavemsg.msgContent
     *
     * @param msgcontent the value for tb_leavemsg.msgContent
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setMsgcontent(String msgcontent) {
        this.msgcontent = msgcontent == null ? null : msgcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_leavemsg.msgtime
     *
     * @return the value of tb_leavemsg.msgtime
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public Date getMsgtime() {
        return msgtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_leavemsg.msgtime
     *
     * @param msgtime the value for tb_leavemsg.msgtime
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setMsgtime(Date msgtime) {
        this.msgtime = msgtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_leavemsg.replyuserid
     *
     * @return the value of tb_leavemsg.replyuserid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getReplyuserid() {
        return replyuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_leavemsg.replyuserid
     *
     * @param replyuserid the value for tb_leavemsg.replyuserid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setReplyuserid(String replyuserid) {
        this.replyuserid = replyuserid == null ? null : replyuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_leavemsg.replycontent
     *
     * @return the value of tb_leavemsg.replycontent
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getReplycontent() {
        return replycontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_leavemsg.replycontent
     *
     * @param replycontent the value for tb_leavemsg.replycontent
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setReplycontent(String replycontent) {
        this.replycontent = replycontent == null ? null : replycontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_leavemsg.replytime
     *
     * @return the value of tb_leavemsg.replytime
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public Date getReplytime() {
        return replytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_leavemsg.replytime
     *
     * @param replytime the value for tb_leavemsg.replytime
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setReplytime(Date replytime) {
        this.replytime = replytime;
    }

    public String getWorkid() {
        return workid;
    }

    public void setWorkid(String workid) {
        this.workid = workid;
    }

    public String getMerchid() {
        return merchid;
    }

    public void setMerchid(String merchid) {
        this.merchid = merchid;
    }
}