package com.hnqj.model;

import java.util.Date;

public class Merchcycle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchcycle.uid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchcycle.merchid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String merchid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchcycle.accountprice
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String accountprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchcycle.addtime
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private Date addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchcycle.auditID
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String auditid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchcycle.audittime
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private Date audittime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchcycle.prevture
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private Double prevture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merchcycle.fcbl
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private Double fcbl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchcycle.uid
     *
     * @return the value of tb_merchcycle.uid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchcycle.uid
     *
     * @param uid the value for tb_merchcycle.uid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchcycle.merchid
     *
     * @return the value of tb_merchcycle.merchid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getMerchid() {
        return merchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchcycle.merchid
     *
     * @param merchid the value for tb_merchcycle.merchid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setMerchid(String merchid) {
        this.merchid = merchid == null ? null : merchid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchcycle.accountprice
     *
     * @return the value of tb_merchcycle.accountprice
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getAccountprice() {
        return accountprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchcycle.accountprice
     *
     * @param accountprice the value for tb_merchcycle.accountprice
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setAccountprice(String accountprice) {
        this.accountprice = accountprice == null ? null : accountprice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchcycle.addtime
     *
     * @return the value of tb_merchcycle.addtime
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchcycle.addtime
     *
     * @param addtime the value for tb_merchcycle.addtime
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchcycle.auditID
     *
     * @return the value of tb_merchcycle.auditID
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getAuditid() {
        return auditid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchcycle.auditID
     *
     * @param auditid the value for tb_merchcycle.auditID
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setAuditid(String auditid) {
        this.auditid = auditid == null ? null : auditid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchcycle.audittime
     *
     * @return the value of tb_merchcycle.audittime
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public Date getAudittime() {
        return audittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchcycle.audittime
     *
     * @param audittime the value for tb_merchcycle.audittime
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setAudittime(Date audittime) {
        this.audittime = audittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchcycle.prevture
     *
     * @return the value of tb_merchcycle.prevture
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public Double getPrevture() {
        return prevture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchcycle.prevture
     *
     * @param prevture the value for tb_merchcycle.prevture
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setPrevture(Double prevture) {
        this.prevture = prevture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merchcycle.fcbl
     *
     * @return the value of tb_merchcycle.fcbl
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public Double getFcbl() {
        return fcbl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merchcycle.fcbl
     *
     * @param fcbl the value for tb_merchcycle.fcbl
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setFcbl(Double fcbl) {
        this.fcbl = fcbl;
    }
}