package com.hnqj.model;

import java.util.Date;

public class Merch {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merch.uid
     *
     * @mbg.generated Tue Jan 09 16:28:58 CST 2018
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merch.merchname
     *
     * @mbg.generated Tue Jan 09 16:28:58 CST 2018
     */
    private String merchname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merch.userinfouid
     *
     * @mbg.generated Tue Jan 09 16:28:58 CST 2018
     */
    private String userinfouid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merch.bondvalue
     *
     * @mbg.generated Tue Jan 09 16:28:58 CST 2018
     */
    private Integer bondvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merch.builddatetime
     *
     * @mbg.generated Tue Jan 09 16:28:58 CST 2018
     */
    private Date builddatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merch.merchscroe
     *
     * @mbg.generated Tue Jan 09 16:28:58 CST 2018
     */
    private double merchscroe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merch.statu
     *
     * @mbg.generated Tue Jan 09 16:28:58 CST 2018
     */
    private Short statu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merch.cycle
     *
     * @mbg.generated Tue Jan 09 16:28:58 CST 2018
     */
    private String cycle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merch.worksnums
     *
     * @mbg.generated Tue Jan 09 16:28:58 CST 2018
     */
    private Integer worksnums;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merch.dealnums
     *
     * @mbg.generated Tue Jan 09 16:28:58 CST 2018
     */
    private Integer dealnums;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_merch.remark
     *
     * @mbg.generated Tue Jan 09 16:28:58 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merch.uid
     *
     * @return the value of tb_merch.uid
     *
     * @mbg.generated Tue Jan 09 16:28:58 CST 2018
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merch.uid
     *
     * @param uid the value for tb_merch.uid
     *
     * @mbg.generated Tue Jan 09 16:28:58 CST 2018
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merch.merchname
     *
     * @return the value of tb_merch.merchname
     *
     * @mbg.generated Tue Jan 09 16:28:58 CST 2018
     */
    public String getMerchname() {
        return merchname==null?"":merchname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merch.merchname
     *
     * @param merchname the value for tb_merch.merchname
     *
     * @mbg.generated Tue Jan 09 16:28:58 CST 2018
     */
    public void setMerchname(String merchname) {
        this.merchname = merchname == null ? null : merchname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merch.userinfouid
     *
     * @return the value of tb_merch.userinfouid
     *
     * @mbg.generated Tue Jan 09 16:28:58 CST 2018
     */
    public String getUserinfouid() {
        return userinfouid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merch.userinfouid
     *
     * @param userinfouid the value for tb_merch.userinfouid
     *
     * @mbg.generated Tue Jan 09 16:28:58 CST 2018
     */
    public void setUserinfouid(String userinfouid) {
        this.userinfouid = userinfouid == null ? null : userinfouid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merch.bondvalue
     *
     * @return the value of tb_merch.bondvalue
     *
     * @mbg.generated Tue Jan 09 16:28:58 CST 2018
     */
    public Integer getBondvalue() {
        return bondvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merch.bondvalue
     *
     * @param bondvalue the value for tb_merch.bondvalue
     *
     * @mbg.generated Tue Jan 09 16:28:58 CST 2018
     */
    public void setBondvalue(Integer bondvalue) {
        this.bondvalue = bondvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merch.builddatetime
     *
     * @return the value of tb_merch.builddatetime
     *
     * @mbg.generated Tue Jan 09 16:28:58 CST 2018
     */
    public Date getBuilddatetime() {
        return builddatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merch.builddatetime
     *
     * @param builddatetime the value for tb_merch.builddatetime
     *
     * @mbg.generated Tue Jan 09 16:28:58 CST 2018
     */
    public void setBuilddatetime(Date builddatetime) {
        this.builddatetime = builddatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merch.merchscroe
     *
     * @return the value of tb_merch.merchscroe
     *
     * @mbg.generated Tue Jan 09 16:28:58 CST 2018
     */
    public double getMerchscroe() {
        return merchscroe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merch.merchscroe
     *
     * @param merchscroe the value for tb_merch.merchscroe
     *
     * @mbg.generated Tue Jan 09 16:28:58 CST 2018
     */
    public void setMerchscroe(double merchscroe) {
        this.merchscroe = merchscroe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merch.statu
     *
     * @return the value of tb_merch.statu
     *
     * @mbg.generated Tue Jan 09 16:28:58 CST 2018
     */
    public Short getStatu() {
        return statu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merch.statu
     *
     * @param statu the value for tb_merch.statu
     *
     * @mbg.generated Tue Jan 09 16:28:58 CST 2018
     */
    public void setStatu(Short statu) {
        this.statu = statu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merch.cycle
     *
     * @return the value of tb_merch.cycle
     *
     * @mbg.generated Tue Jan 09 16:28:58 CST 2018
     */
    public String getCycle() {
        return cycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merch.cycle
     *
     * @param cycle the value for tb_merch.cycle
     *
     * @mbg.generated Tue Jan 09 16:28:58 CST 2018
     */
    public void setCycle(String cycle) {
        this.cycle = cycle == null ? null : cycle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merch.worksnums
     *
     * @return the value of tb_merch.worksnums
     *
     * @mbg.generated Tue Jan 09 16:28:58 CST 2018
     */
    public Integer getWorksnums() {
        return worksnums==null?0:worksnums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merch.worksnums
     *
     * @param worksnums the value for tb_merch.worksnums
     *
     * @mbg.generated Tue Jan 09 16:28:58 CST 2018
     */
    public void setWorksnums(Integer worksnums) {
        this.worksnums = worksnums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merch.dealnums
     *
     * @return the value of tb_merch.dealnums
     *
     * @mbg.generated Tue Jan 09 16:28:58 CST 2018
     */
    public Integer getDealnums() {
        return dealnums==null?0:dealnums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merch.dealnums
     *
     * @param dealnums the value for tb_merch.dealnums
     *
     * @mbg.generated Tue Jan 09 16:28:58 CST 2018
     */
    public void setDealnums(Integer dealnums) {
        this.dealnums = dealnums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_merch.remark
     *
     * @return the value of tb_merch.remark
     *
     * @mbg.generated Tue Jan 09 16:28:58 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_merch.remark
     *
     * @param remark the value for tb_merch.remark
     *
     * @mbg.generated Tue Jan 09 16:28:58 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}