package com.hnqj.model;

public class PropsImage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_props_image.uid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_props_image.props_id
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String propsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_props_image.img_url
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private Integer imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_props_image.img_memo
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String imgMemo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_props_image.uid
     *
     * @return the value of tb_props_image.uid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_props_image.uid
     *
     * @param uid the value for tb_props_image.uid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_props_image.props_id
     *
     * @return the value of tb_props_image.props_id
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getPropsId() {
        return propsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_props_image.props_id
     *
     * @param propsId the value for tb_props_image.props_id
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setPropsId(String propsId) {
        this.propsId = propsId == null ? null : propsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_props_image.img_url
     *
     * @return the value of tb_props_image.img_url
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public Integer getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_props_image.img_url
     *
     * @param imgUrl the value for tb_props_image.img_url
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setImgUrl(Integer imgUrl) {
        this.imgUrl = imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_props_image.img_memo
     *
     * @return the value of tb_props_image.img_memo
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getImgMemo() {
        return imgMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_props_image.img_memo
     *
     * @param imgMemo the value for tb_props_image.img_memo
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setImgMemo(String imgMemo) {
        this.imgMemo = imgMemo == null ? null : imgMemo.trim();
    }
}