package com.hnqj.model;

import java.util.Date;

public class Props {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_props.uid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_props.class_id
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String classId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_props.prop_name
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String propName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_props.prop_remark
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String propRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_props.prop_unit
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String propUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_props.prop_phone
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String propPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_props.prop_price
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private Double propPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_props.CreatorId
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String creatorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_props.CreatorName
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String creatorname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_props.CreateDate
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private Date createdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_props.uid
     *
     * @return the value of tb_props.uid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_props.uid
     *
     * @param uid the value for tb_props.uid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_props.class_id
     *
     * @return the value of tb_props.class_id
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_props.class_id
     *
     * @param classId the value for tb_props.class_id
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setClassId(String classId) {
        this.classId = classId == null ? null : classId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_props.prop_name
     *
     * @return the value of tb_props.prop_name
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getPropName() {
        return propName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_props.prop_name
     *
     * @param propName the value for tb_props.prop_name
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setPropName(String propName) {
        this.propName = propName == null ? null : propName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_props.prop_remark
     *
     * @return the value of tb_props.prop_remark
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getPropRemark() {
        return propRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_props.prop_remark
     *
     * @param propRemark the value for tb_props.prop_remark
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setPropRemark(String propRemark) {
        this.propRemark = propRemark == null ? null : propRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_props.prop_unit
     *
     * @return the value of tb_props.prop_unit
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getPropUnit() {
        return propUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_props.prop_unit
     *
     * @param propUnit the value for tb_props.prop_unit
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setPropUnit(String propUnit) {
        this.propUnit = propUnit == null ? null : propUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_props.prop_phone
     *
     * @return the value of tb_props.prop_phone
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getPropPhone() {
        return propPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_props.prop_phone
     *
     * @param propPhone the value for tb_props.prop_phone
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setPropPhone(String propPhone) {
        this.propPhone = propPhone == null ? null : propPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_props.prop_price
     *
     * @return the value of tb_props.prop_price
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public Double getPropPrice() {
        return propPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_props.prop_price
     *
     * @param propPrice the value for tb_props.prop_price
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setPropPrice(Double propPrice) {
        this.propPrice = propPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_props.CreatorId
     *
     * @return the value of tb_props.CreatorId
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getCreatorid() {
        return creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_props.CreatorId
     *
     * @param creatorid the value for tb_props.CreatorId
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setCreatorid(String creatorid) {
        this.creatorid = creatorid == null ? null : creatorid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_props.CreatorName
     *
     * @return the value of tb_props.CreatorName
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getCreatorname() {
        return creatorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_props.CreatorName
     *
     * @param creatorname the value for tb_props.CreatorName
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setCreatorname(String creatorname) {
        this.creatorname = creatorname == null ? null : creatorname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_props.CreateDate
     *
     * @return the value of tb_props.CreateDate
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_props.CreateDate
     *
     * @param createdate the value for tb_props.CreateDate
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
}