package com.hnqj.model;

import java.math.BigDecimal;
import java.util.Date;

public class Releaseadvert {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_releaseadvert.aduid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String aduid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_releaseadvert.adpositionid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String adpositionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_releaseadvert.adprice
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private BigDecimal adprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_releaseadvert.imgurl
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String imgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_releaseadvert.createtime
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_releaseadvert.clickcount
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String clickcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_releaseadvert.clientuid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String clientuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_releaseadvert.creator
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_releaseadvert.starttime
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private Date starttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_releaseadvert.endtime
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_releaseadvert.adtype
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String adtype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_releaseadvert.aduid
     *
     * @return the value of tb_releaseadvert.aduid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getAduid() {
        return aduid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_releaseadvert.aduid
     *
     * @param aduid the value for tb_releaseadvert.aduid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setAduid(String aduid) {
        this.aduid = aduid == null ? null : aduid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_releaseadvert.adpositionid
     *
     * @return the value of tb_releaseadvert.adpositionid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getAdpositionid() {
        return adpositionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_releaseadvert.adpositionid
     *
     * @param adpositionid the value for tb_releaseadvert.adpositionid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setAdpositionid(String adpositionid) {
        this.adpositionid = adpositionid == null ? null : adpositionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_releaseadvert.adprice
     *
     * @return the value of tb_releaseadvert.adprice
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public BigDecimal getAdprice() {
        return adprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_releaseadvert.adprice
     *
     * @param adprice the value for tb_releaseadvert.adprice
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setAdprice(BigDecimal adprice) {
        this.adprice = adprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_releaseadvert.imgurl
     *
     * @return the value of tb_releaseadvert.imgurl
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_releaseadvert.imgurl
     *
     * @param imgurl the value for tb_releaseadvert.imgurl
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_releaseadvert.createtime
     *
     * @return the value of tb_releaseadvert.createtime
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_releaseadvert.createtime
     *
     * @param createtime the value for tb_releaseadvert.createtime
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_releaseadvert.clickcount
     *
     * @return the value of tb_releaseadvert.clickcount
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getClickcount() {
        return clickcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_releaseadvert.clickcount
     *
     * @param clickcount the value for tb_releaseadvert.clickcount
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setClickcount(String clickcount) {
        this.clickcount = clickcount == null ? null : clickcount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_releaseadvert.clientuid
     *
     * @return the value of tb_releaseadvert.clientuid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getClientuid() {
        return clientuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_releaseadvert.clientuid
     *
     * @param clientuid the value for tb_releaseadvert.clientuid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setClientuid(String clientuid) {
        this.clientuid = clientuid == null ? null : clientuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_releaseadvert.creator
     *
     * @return the value of tb_releaseadvert.creator
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_releaseadvert.creator
     *
     * @param creator the value for tb_releaseadvert.creator
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_releaseadvert.starttime
     *
     * @return the value of tb_releaseadvert.starttime
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_releaseadvert.starttime
     *
     * @param starttime the value for tb_releaseadvert.starttime
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_releaseadvert.endtime
     *
     * @return the value of tb_releaseadvert.endtime
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_releaseadvert.endtime
     *
     * @param endtime the value for tb_releaseadvert.endtime
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_releaseadvert.adtype
     *
     * @return the value of tb_releaseadvert.adtype
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getAdtype() {
        return adtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_releaseadvert.adtype
     *
     * @param adtype the value for tb_releaseadvert.adtype
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setAdtype(String adtype) {
        this.adtype = adtype == null ? null : adtype.trim();
    }
}