package com.hnqj.model;

import java.util.Date;

public class Submission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_submission.uid
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_submission.finduid
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    private String finduid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_submission.worksname
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    private String worksname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_submission.uptime
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    private Date uptime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_submission.samllurl
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    private String samllurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_submission.worksurl
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    private String worksurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_submission.watermakeurl
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    private String watermakeurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_submission.dpinum
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    private String dpinum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_submission.imgsize
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    private String imgsize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_submission.imgformart
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    private String imgformart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_submission.colrmodel
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    private String colrmodel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_submission.favcount
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    private Integer favcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_submission.displayflag
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    private String displayflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_submission.delflag
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    private String delflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_submission.checkuser
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    private String checkuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_submission.chacktime
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    private Date chacktime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_submission.userid
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_submission.ticknums
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    private Integer ticknums;

    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_submission.uid
     *
     * @return the value of tb_submission.uid
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_submission.uid
     *
     * @param uid the value for tb_submission.uid
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_submission.finduid
     *
     * @return the value of tb_submission.finduid
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public String getFinduid() {
        return finduid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_submission.finduid
     *
     * @param finduid the value for tb_submission.finduid
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public void setFinduid(String finduid) {
        this.finduid = finduid == null ? null : finduid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_submission.worksname
     *
     * @return the value of tb_submission.worksname
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public String getWorksname() {
        return worksname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_submission.worksname
     *
     * @param worksname the value for tb_submission.worksname
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public void setWorksname(String worksname) {
        this.worksname = worksname == null ? null : worksname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_submission.uptime
     *
     * @return the value of tb_submission.uptime
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public Date getUptime() {
        return uptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_submission.uptime
     *
     * @param uptime the value for tb_submission.uptime
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public void setUptime(Date uptime) {
        this.uptime = uptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_submission.samllurl
     *
     * @return the value of tb_submission.samllurl
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public String getSamllurl() {
        return samllurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_submission.samllurl
     *
     * @param samllurl the value for tb_submission.samllurl
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public void setSamllurl(String samllurl) {
        this.samllurl = samllurl == null ? null : samllurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_submission.worksurl
     *
     * @return the value of tb_submission.worksurl
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public String getWorksurl() {
        return worksurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_submission.worksurl
     *
     * @param worksurl the value for tb_submission.worksurl
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public void setWorksurl(String worksurl) {
        this.worksurl = worksurl == null ? null : worksurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_submission.watermakeurl
     *
     * @return the value of tb_submission.watermakeurl
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public String getWatermakeurl() {
        return watermakeurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_submission.watermakeurl
     *
     * @param watermakeurl the value for tb_submission.watermakeurl
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public void setWatermakeurl(String watermakeurl) {
        this.watermakeurl = watermakeurl == null ? null : watermakeurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_submission.dpinum
     *
     * @return the value of tb_submission.dpinum
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public String getDpinum() {
        return dpinum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_submission.dpinum
     *
     * @param dpinum the value for tb_submission.dpinum
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public void setDpinum(String dpinum) {
        this.dpinum = dpinum == null ? null : dpinum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_submission.imgsize
     *
     * @return the value of tb_submission.imgsize
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public String getImgsize() {
        return imgsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_submission.imgsize
     *
     * @param imgsize the value for tb_submission.imgsize
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public void setImgsize(String imgsize) {
        this.imgsize = imgsize == null ? null : imgsize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_submission.imgformart
     *
     * @return the value of tb_submission.imgformart
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public String getImgformart() {
        return imgformart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_submission.imgformart
     *
     * @param imgformart the value for tb_submission.imgformart
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public void setImgformart(String imgformart) {
        this.imgformart = imgformart == null ? null : imgformart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_submission.colrmodel
     *
     * @return the value of tb_submission.colrmodel
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public String getColrmodel() {
        return colrmodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_submission.colrmodel
     *
     * @param colrmodel the value for tb_submission.colrmodel
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public void setColrmodel(String colrmodel) {
        this.colrmodel = colrmodel == null ? null : colrmodel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_submission.favcount
     *
     * @return the value of tb_submission.favcount
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public Integer getFavcount() {
        return favcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_submission.favcount
     *
     * @param favcount the value for tb_submission.favcount
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public void setFavcount(Integer favcount) {
        this.favcount = favcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_submission.displayflag
     *
     * @return the value of tb_submission.displayflag
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public String getDisplayflag() {
        return displayflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_submission.displayflag
     *
     * @param displayflag the value for tb_submission.displayflag
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public void setDisplayflag(String displayflag) {
        this.displayflag = displayflag == null ? null : displayflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_submission.delflag
     *
     * @return the value of tb_submission.delflag
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public String getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_submission.delflag
     *
     * @param delflag the value for tb_submission.delflag
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public void setDelflag(String delflag) {
        this.delflag = delflag == null ? null : delflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_submission.checkuser
     *
     * @return the value of tb_submission.checkuser
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public String getCheckuser() {
        return checkuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_submission.checkuser
     *
     * @param checkuser the value for tb_submission.checkuser
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public void setCheckuser(String checkuser) {
        this.checkuser = checkuser == null ? null : checkuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_submission.chacktime
     *
     * @return the value of tb_submission.chacktime
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public Date getChacktime() {
        return chacktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_submission.chacktime
     *
     * @param chacktime the value for tb_submission.chacktime
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public void setChacktime(Date chacktime) {
        this.chacktime = chacktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_submission.userid
     *
     * @return the value of tb_submission.userid
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_submission.userid
     *
     * @param userid the value for tb_submission.userid
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_submission.ticknums
     *
     * @return the value of tb_submission.ticknums
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public Integer getTicknums() {
        return ticknums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_submission.ticknums
     *
     * @param ticknums the value for tb_submission.ticknums
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public void setTicknums(Integer ticknums) {
        this.ticknums = ticknums;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }
}