package com.hnqj.model;

import java.util.Date;

public class Train {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_train.teruid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String teruid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_train.trainname
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String trainname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_train.traintime
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String  traintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_train.trainaddress
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String trainaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_train.phone
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_train.logoimg
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String logoimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_train.topflag
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String topflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_train.price
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private Long price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_train.delflag
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String delflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_train.legtime
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String legtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_train.coursename
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String coursename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_train.trainclass
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String trainclass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_train.trainmethod
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String trainmethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_train.traincontent
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String traincontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_train.endtime
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_train.creator
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_train.createtime
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    private String createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_train.teruid
     *
     * @return the value of tb_train.teruid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getTeruid() {
        return teruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_train.teruid
     *
     * @param teruid the value for tb_train.teruid
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setTeruid(String teruid) {
        this.teruid = teruid == null ? null : teruid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_train.trainname
     *
     * @return the value of tb_train.trainname
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getTrainname() {
        return trainname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_train.trainname
     *
     * @param trainname the value for tb_train.trainname
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setTrainname(String trainname) {
        this.trainname = trainname == null ? null : trainname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_train.traintime
     *
     * @return the value of tb_train.traintime
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getTraintime() {
        return traintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_train.traintime
     *
     * @param traintime the value for tb_train.traintime
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setTraintime(String traintime) {
        this.traintime = traintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_train.trainaddress
     *
     * @return the value of tb_train.trainaddress
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getTrainaddress() {
        return trainaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_train.trainaddress
     *
     * @param trainaddress the value for tb_train.trainaddress
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setTrainaddress(String trainaddress) {
        this.trainaddress = trainaddress == null ? null : trainaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_train.phone
     *
     * @return the value of tb_train.phone
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_train.phone
     *
     * @param phone the value for tb_train.phone
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_train.logoimg
     *
     * @return the value of tb_train.logoimg
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getLogoimg() {
        return logoimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_train.logoimg
     *
     * @param logoimg the value for tb_train.logoimg
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setLogoimg(String logoimg) {
        this.logoimg = logoimg == null ? null : logoimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_train.topflag
     *
     * @return the value of tb_train.topflag
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getTopflag() {
        return topflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_train.topflag
     *
     * @param topflag the value for tb_train.topflag
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setTopflag(String topflag) {
        this.topflag = topflag == null ? null : topflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_train.price
     *
     * @return the value of tb_train.price
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_train.price
     *
     * @param price the value for tb_train.price
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_train.delflag
     *
     * @return the value of tb_train.delflag
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_train.delflag
     *
     * @param delflag the value for tb_train.delflag
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setDelflag(String delflag) {
        this.delflag = delflag == null ? null : delflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_train.legtime
     *
     * @return the value of tb_train.legtime
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getLegtime() {
        return legtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_train.legtime
     *
     * @param legtime the value for tb_train.legtime
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setLegtime(String legtime) {
        this.legtime = legtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_train.coursename
     *
     * @return the value of tb_train.coursename
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getCoursename() {
        return coursename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_train.coursename
     *
     * @param coursename the value for tb_train.coursename
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setCoursename(String coursename) {
        this.coursename = coursename == null ? null : coursename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_train.trainclass
     *
     * @return the value of tb_train.trainclass
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getTrainclass() {
        return trainclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_train.trainclass
     *
     * @param trainclass the value for tb_train.trainclass
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setTrainclass(String trainclass) {
        this.trainclass = trainclass == null ? null : trainclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_train.trainmethod
     *
     * @return the value of tb_train.trainmethod
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getTrainmethod() {
        return trainmethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_train.trainmethod
     *
     * @param trainmethod the value for tb_train.trainmethod
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setTrainmethod(String trainmethod) {
        this.trainmethod = trainmethod == null ? null : trainmethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_train.traincontent
     *
     * @return the value of tb_train.traincontent
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getTraincontent() {
        return traincontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_train.traincontent
     *
     * @param traincontent the value for tb_train.traincontent
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setTraincontent(String traincontent) {
        this.traincontent = traincontent == null ? null : traincontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_train.endtime
     *
     * @return the value of tb_train.endtime
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_train.endtime
     *
     * @param endtime the value for tb_train.endtime
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setEndtime(String endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_train.creator
     *
     * @return the value of tb_train.creator
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_train.creator
     *
     * @param creator the value for tb_train.creator
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_train.createtime
     *
     * @return the value of tb_train.createtime
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_train.createtime
     *
     * @param createtime the value for tb_train.createtime
     *
     * @mbg.generated Tue Jan 09 11:34:57 CST 2018
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }
}